### ISSUE TITLE
found extra blank space on username; therefore, user couldn't log in

### ISSUE THREAD

**Issue by tomasro27** [txcsmad/mad-web-app#18]
A user reported they couldn't log in.  The issue was that their username had an extra blank space character at the end.  We should probably check for this.

Also, some people forget their username. Is there a way to recover it?

**Comment by nishanths** [comment]
Fixed by 62a2495b583c7198dbe706a880197378bc67a8ed and 1eecd7db12124dc376cdd501dba4e4315f5de5ed
